- hosts: webserver
  vars:
    user: Stephan.Kulla
    home: /home/s/{{ user }}
    target: "{{ home }}/serlo"
  environment:
    PYTHONPATH: "{{ home }}/simplejson"
  tasks:
    - name: Create directory for team overview
      file:
        path: "{{ target }}"
        state: directory
        owner: "{{ user }}"
        mode: 0755

    - name: Store .htaccess file on server
      template:
        src: htaccess
        dest: "{{ target }}/.htaccess"
        mode: 0440
        owner: "{{ user }}"

    - name: Store .htdigest file on server
      copy:
        src: htdigest
        dest: "{{ target }}/.htdigest"
        mode: 0440
        owner: "{{ user }}"
